### ISSUE TITLE
Clarify difference with collections.namedtuple

### ISSUE THREAD

**Issue by svisser** [jcomo/immut#1]
It may be good to clarify in the README the difference with the `collections.namedtuple` type, which raises AttributeError in invalid cases (trying to assign or trying to access an invalid attribute) - and it also has a name and several fields.

```python
>>> import collections
>>> A = collections.namedtuple('A', ['a', 'b'])
>>> a = A(1, 2)
>>> a.a
1
>>> a.a = 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: can't set attribute
>>> a.x = 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute 'x'
>>> a.xz = 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute 'xz'
```

**Comment by jcomo** [comment]
Didn't even think about namedtuple until now. The main difference in behavior is with the initialization. With namedtuple, each defined attribute needs to be initialized and with this container library, attributes are initialized to None by default. Thanks for taking a look! They're actually pretty darn similar

**Comment by svisser** [comment]
Nice, thanks for clarifying. That indeed is the main difference with namedtuple.
